package banco

import org.springframework.jdbc.core.BeanPropertyRowMapper
import org.springframework.jdbc.core.JdbcTemplate

class Query (private val jdbcTemplate: JdbcTemplate) {

    fun createTable(tipoBanco:Int) {
        if (tipoBanco == 1) {
            jdbcTemplate.execute("""
            SET GLOBAL time_zone = '+3:00';
    """)// Essa função é importante pois essa library de MySQL depende de usar o msm fuso horario que o software!!
            jdbcTemplate.execute("""
        create table IF NOT EXISTS crawlerComponente(
        idComponente int PRIMARY KEY auto_increment,
        nome VARCHAR(45)
        );
    """)
            jdbcTemplate.execute("""
        create table IF NOT EXISTS crawlerSecao(
        idSecao int PRIMARY KEY auto_increment,
        nome VARCHAR(45),
        fkSecao int,
        fkComponente int,
        foreign key (fkSecao) references crawlerSecao(idSecao),
        foreign key (fkComponente) references crawlerComponente(idComponente)
        );
    """)
            jdbcTemplate.execute("""
        create table IF NOT EXISTS crawlerLeitura(
        idLeitura int PRIMARY KEY auto_increment,
        nome VARCHAR(45),
        minimo DECIMAL(9,3),
        valor DECIMAL(9,3),
        maximo DECIMAL(9,3),
        horario CHAR(8),
        dia CHAR(10),
        fkSecao int,
        foreign key (fkSecao) references crawlerSecao(idSecao)
        );
    """)
        } else if (tipoBanco == 2) {
            jdbcTemplate.execute("""
        create table IF NOT EXISTS crawlerComponente(
        idComponente int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(45)
        );
    """)
            jdbcTemplate.execute("""
        create table IF NOT EXISTS crawlerSecao(
        idSecao int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(45),
        fkSecao int,
        fkComponente int,
        foreign key (fkSecao) references crawlerSecao(idSecao),
        foreign key (fkComponente) references crawlerComponente(idComponente)
        );
    """)
            jdbcTemplate.execute("""
        create table IF NOT EXISTS crawlerLeitura(
        idLeitura int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(45),
        minimo DECIMAL(9,3),
        valor DECIMAL(9,3),
        maximo DECIMAL(9,3),
        horario CHAR(8),
        dia CHAR(10),
        fkSecao int,
        foreign key (fkSecao) references crawlerSecao(idSecao)
        );
    """)
        }
    }

    fun insertComponente(nome:String) {
        jdbcTemplate.update("""
            insert into crawlerComponente (nome) values
            (?)
        """, nome)
    }
    fun insertSecao(nome:String, fkComponente:Int) {
        jdbcTemplate.update("""
            insert into crawlerSecao (nome, fkComponente) values
            (?, ?)
        """, nome, fkComponente)
    }fun insertSubsecao(nome:String, fkSecao:Int, fkComponente:Int) {
        jdbcTemplate.update("""
            insert into crawlerSecao (nome, fkSecao, fkComponente) values
            (?, ?, ?)
        """, nome, fkSecao, fkComponente)
    }
    fun insertDados(valores:MutableList<String>, fkSecao:Int) {
        jdbcTemplate.update("""
            insert into crawlerLeitura (nome, minimo, valor, maximo, horario, dia, fkSecao) values
            (?, ?, ?, ?, ?, ?, ?)
        """, valores[0], valores[1], valores[2], valores[3], valores[4], valores[5], fkSecao)
    }

    fun selectIdComponente(nome: String):Int {
        return jdbcTemplate.queryForObject(
            "select idComponente from crawlerComponente where nome = ?",
            BeanPropertyRowMapper(dataComponente::class.java),
            nome
        )!!.idComponente
    }
    fun checarComponente(nome: String):Boolean {
        return jdbcTemplate.queryForObject(
            "select count(*) from crawlerComponente where nome = ?",
            Int::class.java,
            nome
        ) == 0
    }
    fun selectIdSecao(nome: String):Int {
        return jdbcTemplate.queryForObject(
            "select idSecao from crawlerSecao where nome = ?",
            BeanPropertyRowMapper(dataSecao::class.java),
            nome
        )!!.idSecao
    }
    fun checarSecao(nome: String):Boolean {
        return jdbcTemplate.queryForObject(
            "select count(*) from crawlerSecao where nome = ?",
            Int::class.java,
            nome
        ) == 0
    }
}